image: gradle:7.5.1-jdk11

clone:
  depth: full # SonarCloud scanner needs the full history to assign issues properly

definitions:
  steps:
    - step: &buildAndPublish
        name: Build and publish
        trigger: manual
        caches:
          - gradle
        script:
          - ./deploy/injectGradleCredentials.sh "$NEXUS_USERNAME" "$NEXUS_PASSWORD" "gradle.properties"
          - gradle publish --no-daemon

pipelines:
  branches:
    master:
      - step: *buildAndPublish
